### PR TITLE
Make it work with Python 3

### PR DESCRIPTION
**Pull request by ReallyNiceGuy**
Hi. I made some small changes on the to make the version 1.x work with python 3. I didn't test extensively, but my program generates exactly the same output when running under python 2 and python 3. At very least, it does no harm for python 2.7 and above.

### CODE REVIEW

**Comment by jpivarski** [comment]
Thanks! I don't support this anymore, but the 2-to-3 conversions look appropriate.

**Comment by ReallyNiceGuy** [comment]
None of it or just the 1.x? Can you point me to the maintainer, if you happen to know? Thank you.

**Comment by jpivarski** [comment]
None of it. I copied it over from Google Code when that ceased to exist. The last date is something like 2008. I've written two other plotting packages, based on these ideas (see Open Data Group's GitHub page), and my current project is aggregation-only. http://histogrammar.org

These ideas (Grammar of Graphics) were taken further by ggplot2 in R, and Bokeh (many languages) has a nice idea of separating the plot-preparation from the drawing routines, which are all in JavaScript so that your browser becomes the plot window. It uses full HTML5, rather than SVG.

**Comment by ReallyNiceGuy** [comment]
My use case is not browser based. I create some overlays and merge it with a picture using rsvg and imagemagick.
I will get acquainted with this code base, I might take care of it, if it is abandoned.

Cheers.

**Comment by jpivarski** [comment]
Too many plotting libraries are using web browser/Javascript tricks to make plots with guide lines and things on mouseover, which are not often useful for interpreting the data. But I think it's a good idea to use a browser as the plot window for one simple reason: everyone has one. That way, you can interactively monitor your work as you develop it without any graphics dependencies (which are a pain to install).

For an old-fashioned viewer with GTK dependencies, you could use the svgviewer.c bundled in SVGFig, but users will have trouble installing packages like rsvg-dev. I had a better idea on a StackOverflow some time ago:

http://stackoverflow.com/a/16867833/1623645

You can make an interactive viewer in pure Python&mdash; no compilation step&mdash; with a few PyPI dependencies that can be added to the setup.py `requires` section.

If you want to be an admin/owner of this project for the sake of modernizing it (more than you've already done), you're welcome to it. Ask and I'll find the button in Settings to add you.

**Comment by ReallyNiceGuy** [comment]
Yes, I agree with you there. Your idea on stackoverflow is a very nice one.
I don't really have any of that problems. I just create a png file to be sent to a web server. I need to add lines and text that come from a GIS file. For that, this SVGFig is good enough.
I would be happy to help maintaining this code.

**Comment by jpivarski** [comment]
Okay, I'll add you right away.

If your web application views SVG, which can be embedded in any HTML5 nowadays, you could just view the plots without converting to PNG. They'll probably be smaller and faster to transmit, and they'll look good at all scales.

Oh: "merge with a picture." PNGs can be embedded within SVGs, which is something I learned how to do after SVGFig. You read the file, base64-encode it (all from the Python standard library), and make a

```xml
<image xlink:href="data:image/png;base64,BASE64-DATA-HERE"
       x="LEFT" y="TOP" width="WIDTH" height="HEIGHT" />
```

I found this code from a later plotting package of mine: https://github.com/opendatagroup/augustus/blob/master/trunk/augustus-pmml-library/augustus/core/ArrayToPng.py but it does more than you want (it converts a 2D Numpy array into a PNG and embeds it in an SVG).

Anyway, use only as much as you need.
Cheers!

**Comment by ReallyNiceGuy** [comment]
Just so you get a view of the final product. The key phrase is "the client wants a
 picture". I actually embed the picture into the svg, and then render the svg back to an image... ;)

00000_ppi_ppi_zh_2016-05-23t14_39_02 00_00

**Comment by jpivarski** [comment]
Nice! So this is more of a way to annotate an image, rather than what I think of as plotting.

You might find that SVGFig is overkill for this kind of application. You're probably using the SVG primitives, rather than the "Fig" abstraction, and then all you get from SVGFig is a nice mapping of XML onto Python objects. At the time I wrote SVGFig, I didn't realize there was a more standard product, lxml (http://lxml.de/) that does the same thing. (They call it "data binding.")

But if you've already written the application, nothing's easier than leaving things as they are.

**Comment by ReallyNiceGuy** [comment]
Well, I made use of the polylines, text, symbols. It was better than using XML directly. For example, how would I do the following using lxml?
```
s = svgfig.SVG("g")
    s.append(svgfig.Poly(self.points.zipped(), loop=0, 
        stroke=color, stroke_width="1px", fill="none").SVG())
```
Also, I made a lot of symbols. By the way, I couldn't find make_symbols in the new version. Is there a reason?

**Comment by jpivarski** [comment]
In lxml, it looks almost exactly like that, except that they're not Python objects that get printed out as XML, but XML DOM nodes in the libxml.so library installed on most computers. lxml makes proxies on the fly to control the underlying C objects. If I were to switch, the only motivating factor would be that lxml is a well-known library and SVGFig is obscure enough that you'd probably want to embed it in your project to make sure your users can install it.

... Which you can't if you're making a commercial product. I just searched the codebase, and unfortunately, SVGFig uses GPL, so it can only be embedded or linked to in free software. (And that free software can only be used in free software, and so on.) I didn't know about these things when I wrote it, and I don't know under what circumstances a license can be changed. Is your application commercial?

For the time being, here are pointers to SvgBinding and its superclass, XmlBinding from Augustus, which is Apache 2 licensed (free and commerce-friendly). They use lxml to make a data binding similar to the one in SVGFig.

https://github.com/opendatagroup/augustus/blob/master/trunk/augustus-pmml-library/augustus/core/XmlBinding.py
https://github.com/opendatagroup/augustus/blob/master/trunk/augustus-pmml-library/augustus/core/SvgBinding.py

**Comment by ReallyNiceGuy** [comment]
Thanks for the pointer. I will take a deeper look.
The application that generates the underlying data is, but the script that actually does the conversion is given with sources and pointers to all the libraries. Does this comply? If not, I will cease to use it immediately.

**Comment by ReallyNiceGuy** [comment]
About license, it is certainly complicated. If you own all of your code, you can change the license, even retroactively (for a more permissive one, I would say). The problem starts when you accept patches from other people. If you get permission from every contributor, no problem. If you can't, you are probably stuck.

**Comment by jpivarski** [comment]
GPL-code can use commercial products, but commercial products cannot use GPL-code. There's a legal gray area about what "use" means: embed, link in the same distribution, link in separate distributions, etc. "LGPL" is looser about linking, but SVGFig isn't LGPL. In the forward direction, GPL is transitive: anything that uses anything that uses GPL-code has to be given for free, not charged for a price or used internally as part of a commercial organization's business.

It would be legal for a commercial product to make data that gets interpreted by GPL-code, because that's the right direction. Your script, by using SVGFig, cannot be sold or used as part of a commercial organization's business. Are you doing the latter? Is this script for a commercial client? Regardless of whether they intend to sell it or use the processed data, they can't as long as SVGFig is GPL'ed.

If that's the case, look into lxml and my Apache-licensed wrappers on its interface (XmlBinding and SvgBinding). These can be freely copied and used in any product without legal issues. You may be able to reproduce SVGFig's interface exactly (GPL applies to code, not abstract interfaces) and then not have to change your code.

**Comment by ReallyNiceGuy** [comment]
I think that your interpretation is too narrow on the "used as part of a commercial business" part. See: [https://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.en.html#TOCInternalDistribution](url).

I will change my script ASAP, anyway. Thanks for your heads up.
The new version doesn't mention the GPL in any file. Is it also under GPL V2?

**Comment by jpivarski** [comment]
I found it by searching the repository: https://github.com/jpivarski/svgfig/blob/154ee24b84b2707cdb592529a21c4cb8278647a1/svgfig-1.x/svgfig.py It's at the top of the only source file.

**Comment by ReallyNiceGuy** [comment]
Sure, I found that too. I mean the svgfig directory, the new implementation.

**Comment by jpivarski** [comment]
I think the new version is just a sketch, not cleaned up in any sense.

**Comment by jpivarski** [comment]
So the new version is a new codebase that has never even had a license applied to it. If you interpret that liberally, I won't complain at all.

**Comment by ReallyNiceGuy** [comment]
Ok, wink, wink...

Anyway, I will wrap my head around your Augustus library. Looks mature.

Thanks again for your time and help.

**Pull request merged**
